### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by eddiee2000** [ResetXPDR/MSFS2020_AutoFPS#10]
Thought issue might be little nav map so closed that, then noticed internet connection kept dropping out ( I have 1gb fibre to premises) but when I started MSFS2020 Auto FPS I got the following

Regards

Eddie Eves
![IMG_6077](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/86880707/f577dec9-aa30-402b-ba44-e9a55083fe62)

**Comment by ResetXPDR** [comment]
That issue is covered in the readme. The most likely cause is a permissions issue so try running the app as adminstrator.
