### ISSUE TITLE
CONFLICT DETECTING CORRECT ACTUAL FPS WITH POPOUT INSTRUMENTS - TWO SCREENS

### ISSUE THREAD

**Issue by fabianovm** [ResetXPDR/MSFS2020_AutoFPS#11]
Hello, how are you? First of all, congrats and thanks a lot for such a usefull and easy to use tool. Have respect from all community!!!
I found I situation, like an ISSUE when using 2 second monitor: will explain in details the situation:
1)	I start the app MSFS2020_autofps
2)	I start MSFS2020
3)	Start a flight and now , with flight loaded in the sim (maximized, not windowed) , inside cockpit , I give alt+tab and let the AUTOFPS in the front in order to test it during flight…. In this case, everything works perfectly, the AUTOFPS app gets the real active FPS in the main screen, in this case a 70” 4k 60 hz Samsung TV. My main 70” monitor is 60hz, in msfs settings I use dlss quality, 4k resolution, mix of high/ultra and Vsync 50% in order to maintain 30 fps. 

4)	What I do next mess totally with AUTOFPS and my experience in flight.  There is a famous program called SPACEDESK that is like a virtual monitor. There is a server app in windows and a .apk in a 10” Samsung tablet, which in the case is the second screen. Windows recognizes this spacedesk second monitor (wifi tablet) as an extension of the desktop. Continuing… inside cockpit I POP OUT an instrument and drag it to the tablet, the second monitor for windows. Works perfect, I put GTN750 ou GTC3000 touch screens on it.

5)	Now the problem….the main 70” screen works at 60hz, and inside msfs vsync50% on, 30 fps, easy. The tablet/spacedesk have a different FPS from the main screen…. Around 15-20 fps depending of connection (it uses wifi6 1gb to communicate).

When I click on the tablet , still msfs second windows(in fact when I touch an instrument on it) tablet is running for example 15 fps, MSFS2020_AUTOFPS detects THIS fps, from the tablet, and make unnecessary and annoying adjustments to the sim, reducing clouds, LOD, etc…. because it thinks the main screen is running 15 fps, but in fact it is locked at 30 (with a lot of room to increase if I turn off vsync, it is not on the limit) . When I click back to main 70” screen 30fps MSFS2020_AUTOFPS make right adjustments again… if I click or touch another simulator screen, MSFS2020_AUTOFPS start to recognize and correct FPS according to the last clicked/touched screen, not fixed on the main one as we desire.

It is not possible to use (or even see what is happening in fact with MSFS2020_autoFPS, because everytime msfs looses focus, it reports the FPS of the second  msfs screen.

6)	Suggestion: is there any way to add a list, a combo to select the GPU (or the, the screen), on the side of the field ‘target fps’ (SEE PICTURE), in order to teach msfs2020_autofps to ALWAYS look FPS of the select monitor?

![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/86928223/0d9c2fec-65f4-45bd-b0d3-9e83d5e49533)

If you have any other idea for solving this, would be awesome, there are tons of simmers that would love your app but uses several, not just two, screens, like airmanager, spacedesk, etc. Solving this would really consolidate the app as a must-have.

**Comment by ResetXPDR** [comment]
I understand what you are asking for but the app currently gets its MSFS FPS information via simconnect, not per individual MSFS window, not externally and not per attached screen or GPU in use, so it would be a major change to get another reliable source of FPS data related to screens and GPUs. As such, I have no plans to implement such functionality at this time. The code is open source, so if anyone else wants to take what I have developed and make such a change, they are more than welcome.

**Comment by fabianovm** [comment]
@ResetXPDR thanks a lot for fast reply! I TOTTALY understand your point.

All test I did and reported in issue was in 0.4.0.

I just installed 0.4.1 and marked new option "on top" and made all tests again... exactly same settings , flight, location, plug-ins,all the same.

With the "on top" checked on autofps, it works perfect, I can click, touch another msfs screens with lower fps and the app autofps stays always looking for the real fps, mais screen as expected. Perfect.

Now my doubt... if I uncheck "on top" could bring back the bad behavior I reported on issue? What do you think my friend?

**Comment by fabianovm** [comment]
@ResetXPDR thanks a lot for fast reply! I TOTTALY understand your point.

All test I did and reported in issue was in 0.4.0.

I just installed 0.4.1 and marked new option "on top" and made all tests again... exactly same settings , flight, location, plug-ins,all the same.

With the "on top" checked on autofps, it works perfect, I can click, touch another msfs screens with lower fps and the app autofps stays always looking for the real fps, mais screen as expected. Perfect.

Now my doubt... if I uncheck "on top" could bring back the bad behavior I reported on issue? What do you think my friend?
