### ISSUE TITLE
Still getting the MSFS Compatability Test Failed -Read Only Mode.

### ISSUE THREAD

**Issue by WarriorII** [ResetXPDR/MSFS2020_AutoFPS#14]
Is there anything I can do to try and figure out what this isn't working for me?  Could really use the extra FPS but both the original and this version throw that error as soon as I click Fly Now.

**Comment by ResetXPDR** [comment]
Did you see the readme section on this? Do what it says and let me know if that fixed it for you.

**Comment by WarriorII** [comment]
> Did you see the readme section on this? Do what it says and let me know if that fixed it for you.

Yes I read the readme file but didn't see anything that could be changed.  It only talked about reading memory locations.  If I'm missing something please let me know.

**Comment by WarriorII** [comment]
Crap completely missed the run as administrator part. I'll try that in a bit.

**Comment by WarriorII** [comment]
Thank you so much for pointing that out. Works fantastic now!

**Comment by ResetXPDR** [comment]
Glad I could help. I will close this now.
