### ISSUE TITLE
I was able to record the operating status in VR using an inexpensive video capture device.(What I would like to ask if possible)

### ISSUE THREAD

**Issue by Yfl411** [ResetXPDR/MSFS2020_AutoFPS#18]
I am using translation software from Japan. I apologize for any inconvenience caused by my writing.

[https://youtu.be/BmY6gMrk444](https://youtu.be/BmY6gMrk444)

It's a great tool that I wish I had.
I prefer the odd flight of videos, but the effect was felt immediately.
By moving to the bottom left of the mirror image of Pimax8kx, I was able to pass HDMI and record simultaneously with the capture unit.

Due to the night view, the screen gamma value on the PC side is increased in NVIDIA properties.
This is why it is whitish.

I felt it would be nice if there was a high-contrast color mode and a minimal display mode.

The test flight course I like doesn't usually have changes in altitude, so I feel like I need to make detailed settings.

At the moment, buildings drawn by mods sometimes disappear (this seems to happen at high FPS settings).
There is a stutter that was not there before (as far as I can see the numbers, it has nothing to do with LOD or cloud changes. It is probably not caused by AUTOFPS.
The culprit is a different limitation of the PC. I think it came out due to improved FPS)

For the first time in a while, I saw a ray of hope.
thank you.

**Comment by ResetXPDR** [comment]
If I am reading what I think you are saying, this tool has improved your flight sim experience. If so, I am very pleased for you and hope that it continues to do so. I will close this issue as I am pretty sure this is just feedback rather than an issue. Let me know if otherwise and I will reopen it.
