### ISSUE TITLE
Not really an Issue then a Request

### ISSUE THREAD

**Issue by mroschk** [ResetXPDR/MSFS2020_AutoFPS#19]
Hello,
since i have 3 Big Screens and so i need to lower the LOD a bit to get accepable FPS, i want to kindly ask if you can add one Option in the next Version.
After landing and during the Taxi to the Gate all works fine with a little lower LOD.
But then, when i am at the Gate, so the speed is back to 0 kt GS, i often have a look from outside at the Airport or at GSX.
For this i want to request the Option to set a higher LOD.
So if the Speed is 0, the LOD can be back to higher values.

Thanks
Matthias

**Comment by ResetXPDR** [comment]
You can already do that by setting your TLOD Min to a higher value when you are at the gate and your TLOD will instantly change to that with no stepping, then change it back again when you are finished.

Alternatively you can uncheck TLOD Min on ground/landing when you are at the gate and your TLOD will rise to meet your target FPS, then check it again when you are finished. Just be aware that if you are using DX12 this is know to exacerbate tearing issues of airport ground textures. 

Give each of these a try and see how you go.

**Comment by mroschk** [comment]
Hello,
gave it a try, but thats not really what i am looking for.
Could you not add a checkbox and a TLOD+OLOD Setting for if the Groundspeed is zero ?

**Comment by ResetXPDR** [comment]
That is precisely what the second option I gave, uncheck TLOD Min on ground/landing, already does. Are you sure you tried it?

**Comment by mroschk** [comment]
Yes i think so, but will try tomorrow again ...

**Comment by ResetXPDR** [comment]
Either way, thank you for your suggestion but since what you want can be achieved in other ways, including using DynamicLOD_ResetEdition instead which provides more flexibility with such things, and I do not wish to add more options that are very similar to what is already there, I will not be implementing your proposal.
