### ISSUE TITLE
Connection Status

### ISSUE THREAD

**Issue by Deltaflight84** [ResetXPDR/MSFS2020_AutoFPS#20]
I just wonder why my connection status is always in grey color? and the TLOD does not never increase plus 50
thx in advance

**Comment by Deltaflight84** [comment]
[MSFS2020_AutoFPS20240303.log](https://github.com/ResetXPDR/MSFS2020_AutoFPS/files/14474101/MSFS2020_AutoFPS20240303.log)

**Comment by ResetXPDR** [comment]
Looks like it is working OK from your log file because it doesn't save and restore MSFS settings unless all three connections are green. Can you post a screenshot of the app when it is doing what you say it is.

**Comment by Deltaflight84** [comment]
![FlightSimulator_223](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/76566744/6b3d8f56-56ed-4b8c-9a41-2bd5d9885ded)

**Comment by ResetXPDR** [comment]
Your connection statuses are showing green not grey and that is how it should be.

Your TLOD is not going above 50 because you are not getting high enough FPS above your target FPS for TLOD to increase.

I strongly suggest you read through the readme in detail as your issues are program use related, not issues with the app itself.

**Comment by Deltaflight84** [comment]
Maybe because i have my fps blocked at 30 fps? I don't want the fps at 60.

Il lun 4 mar 2024, 22:58 ResetXPDR ***@***.***> ha scritto:

**Comment by ResetXPDR** [comment]
You can't have your FPS target set to the same value as any FPS cap you have set. Again this is covered in the readme. I am going to close this issue as it is not a problem with the program, rather it is an issue with you not understanding how to use the program and that is what the readme is for.
