### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by nivlqC** [ResetXPDR/MSFS2020_AutoFPS#21]
So i just had this idea for this, and i cant get it off my mind. So what if instead of TLOD Minimum on landing/ground, it was like a set amount, like 100 as an ex, then the amount is increased higher as you go up immedately to like 150 then it can go from x - y, that way you get good fps, but then after you depart instead of staying for a little bit at the minimum it goes up some.

probably a stupid idea, and sorry if it is for wasting your time, but thanks either way for this addon

**Comment by ResetXPDR** [comment]
DynamicLOD_Reset Edition already does that kind of thing, so I will close this issue to that. Check it out [here](https://github.com/ResetXPDR/DynamicLOD_ResetEdition)
