### ISSUE TITLE
When you return to the world map after flying using AutoFPS

### ISSUE THREAD

**Issue by ddobagi810** [ResetXPDR/MSFS2020_AutoFPS#25]
When you return to the world map after flying using AutoFPS, the AutoFPS add-on's 
I see the simconnect and session in red text.
I don't know why the simconnect is disconnected.
Also, the buttons on the main screen (like quit game) are most likely unresponsive when the simconnect is in red text.

**Comment by ResetXPDR** [comment]
I've not heard of this one before. Was this a one off or have you seen it multiple times and between system reboots?

**Comment by ddobagi810** [comment]
> I've not heard of this one before. Was this a one off or have you seen it multiple times and between system reboots?

always.

**Comment by ResetXPDR** [comment]
The only things I can suggest is making sure your MobiFlight is up to date and that you don't have conflicting versions in your community and official folders. Also, try disabling your AV temporarily while running MSFS and the app and if that resolves it try setting exclusions for these in your AV program.

**Comment by ddobagi810** [comment]
what is AV?

**Comment by ddobagi810** [comment]
> what is AV?  Anti-Virus?

**Comment by ResetXPDR** [comment]
Anti Virus
