### ISSUE TITLE
AutoFPS in Vr

### ISSUE THREAD

**Issue by Ronnielib** [ResetXPDR/MSFS2020_AutoFPS#26]
Got the App working, but is there a way I can view it and make changes while in Vr?

**Comment by ResetXPDR** [comment]
Other than ways you can bring other non-VR windows into your VR session with existing tools out there, no you can't view this app's UI directly in VR and I am not intending to implement such a feature.

**Comment by Ronnielib** [comment]
Thank you, I'll do some research. Thank you for your great work on this app, it's amazing, even in VR, huge difference.

**Comment by ResetXPDR** [comment]
You are welcome and I hope you continue to enjoy using this app.
