### ISSUE TITLE
Thank you for creating Autofps.

### ISSUE THREAD

**Issue by ddobagi810** [ResetXPDR/MSFS2020_AutoFPS#27]
Thank you for creating Autofps.
There is an (x) in the upper right corner of the program.
However, the (X) goes to the system tray instead of exiting.
If it's not too difficult, is it possible to make it possible to select ( _ X )?
where ( _ ) is the system tray. Is it possible for ( x ) to exit the program?

I get a CTD every once in a while, so I turn on the program at the airport, and I get the 
After the flight, I exit the program and go to the world map.

**Comment by ResetXPDR** [comment]
While this is something I may have done in the future, I have decided to finish up with AutoFPS after the next nearly-finalised version is released in the next few days, so unfortunately I won't get to this. Nonetheless, you can currently close the app from the system tray (right click then select exit) or the app will exit by itself when you quit MSFS. There will also be a minimise button in the next version.
