### ISSUE TITLE
Save window startup position?

### ISSUE THREAD

**Issue by dflachbart** [ResetXPDR/MSFS2020_AutoFPS#28]
First of all, thank you so much for this fantastic tool!!

I like to have the window open all the time, and I always tuck it away into the upper right corner of my second monitor as soon as it starts up. Would it be possible to add an option to save the current window position when you exit the program, so that it gets automatically restored on the next startup?

**Comment by ResetXPDR** [comment]
You are welcome. This item is already on the wish list.

**Comment by dflachbart** [comment]
Hi, is this in the latest 0.4.2 version (the issue shows as 'completed')? It doesn't seem to be working for me. Anything I have to configure?

**Comment by ResetXPDR** [comment]
It is completed in that it was added to the wish list. It is not in 0.4.2, however I managed to get it working in a test build yesterday and may put it up as a pre-release for you to try if you like. I haven't worked out how to put the app on a specific monitor but it seems to be putting app back in the previous location on my second monitor, so it seems to be working

**Comment by dflachbart** [comment]
Ah I misunderstood the status then. But if you already have something working then of course I'd love to try it out, but no rush... Thanks!

**Comment by ResetXPDR** [comment]
I'll put a reply here when I put up the test version, which should be in the next couple of hours. Your feedback on it would be appreciated.

**Comment by ResetXPDR** [comment]
@dflachbart a test build with the new window position saving code has been made and can be found [here](https://github.com/ResetXPDR/MSFS2020_AutoFPS/releases/tag/v0.4.3-test).

**Comment by dflachbart** [comment]
This works perfectly! I have a 3-monitor setup and tested positions on both left and right, they get saved and restored fine. Thanks again for implementing this! 🎊

**Comment by ResetXPDR** [comment]
No worries. While it works for me with multi-monitors it seems to get thrown by switching in and out of VR, where I have lost the window completely until I shut down and restart the app where it comes back positioned where expected so I don't know what's going on with that yet.  If I can't resolve it, I will still leave in the save/restore window position but it might be disabled by default and the user will have to enable it in the config file otherwise I may upset the app's VR user base. ie. you will still be able to use it one way or another.

**Comment by ResetXPDR** [comment]
I am having an issue with it not opening up properly when auto-started with MSFS. Nonetheless, the final version will at least have a config file enable option even if I can't fix it. I will close this as being already planned.
