### ISSUE TITLE
PC is slow after auto fps 

### ISSUE THREAD

**Issue by Bolmlht** [ResetXPDR/MSFS2020_AutoFPS#29]
Hey, 
I installed auto fps for msfs version 0.4.0 and updated it to 0.4.1 after opening it. I used it once, had 15 fps, not the 60 I've set. So I deinstalled it because I have more frames without it. The point is that after I used it my whole PC is slow af, especially when I play msfs (Fenix A320 v2.0.0.378; FS2Crew v1.2.205; GSX v2.9.4; FSRealistic v.2.2.1; vPilot v.3.8.1). vPilot crashes all the time tue to it for example. Or my Windows search wont work properly because it always hangs. Before I used auto fps I never had such problems and didn't installed anything since auto fps, so it has to be the issue.

**Comment by ResetXPDR** [comment]
This app only installs to its own directory, and adds an icon and autostart if you chose those options. When running, it only ever interacted with MSFS in memory, not the executable itself, and doesn't change anything permanently. If you ran the installer to uninstall it, it removes all of those items and hence any trace that it has been on your system.  So as much as you think this app is causing your sudden slow down issue, even after uninstalling it, I can assure you it is not. Try running a virus or malware scan and see if something else got on your system around the same time as you updated this app.
