### ISSUE TITLE
Cannot disable auto pause

### ISSUE THREAD

**Issue by MrVern** [ResetXPDR/MSFS2020_AutoFPS#3]
When i bring up this app as an overlay it auto pauses.
Have no idea where to turn it off, let alone turn it on

**Comment by aurel42** [comment]
Are you aware of "Use Expert Options" -> "Pause when MSFS loses focus"?

**Comment by MrVern** [comment]
I am 
box is not checked but it still will auto pause

**Comment by aurel42** [comment]
I'm using 0.4.1 (the pre-release) and it appears to work for me, but it also appeared to work for me on 0.4.0.
(Standard disclaimer: This does not imply that I doubt it doesn't work for you.)

**Comment by ResetXPDR** [comment]
Auto pause is covered in the last dot point in the readme, so unless it is not behaving as stated, I will close this issue. 

In short, to disable auto pause, check Use Expert Options and then uncheck Pause when MSFS loses focus.
