### ISSUE TITLE
Cloud settings gets always sets to HIGH

### ISSUE THREAD

**Issue by TheFlyingDutchman77** [ResetXPDR/MSFS2020_AutoFPS#31]
First of all: Absolutely loving this app. Many thanks!!!

Question: Even with 'Decrease Cloud Quality' disabled, AutoFPS keeps resetting my cloud quality to HIGH. Is that intended behaviour?

**Comment by ResetXPDR** [comment]
The readme says this on it: 
- Decrease Cloud Quality - When enabled, will reduce cloud quality by one level if TLOD has already auto reduced to TLOD Min and FPS is still below target FPS by more than the FPS tolerance. When expert settings are disabled, the app will enable this setting.

also

- Do not change TLOD, OLOD and Cloud Quality MSFS settings manually while in a flight with this app running as it will conflict with what the app is managing and they will not restore to what you set when you exit your flight. If you wish to change the defaults for these MSFS settings, you must do so either without this app running or, if it is, only while you are in the MSFS main menu (ie not in a flight).

Is something happening different to these descriptions? If so, please be very specific.

**Comment by ResetXPDR** [comment]
Cloud quality has been reworked in version 0.4.2 that will be released tomorrow, so this issue should be now resolved.
