### ISSUE TITLE
Get us out of the shadowy underworld of MSFS "illegal" mods

### ISSUE THREAD

**Issue by ToddLorey** [ResetXPDR/MSFS2020_AutoFPS#33]
Since this awesome program was alluded to during today's dev stream, I decided to write up a wishlist item that can get this out into the open.  After some back and forth with the moderators, edits to make the legal team happy and winning my supreme court appeal, they let it pass.  Check it out here:

https://forums.flightsimulator.com/t/expose-tlod-olod-clouds-etc-via-simconnect-l-vars/634075

And vote if you think it's a good idea.

p.s.  Thank you for making this program.  It has literally transformed my sim experience.  You rock!

**Comment by ResetXPDR** [comment]
I think that's a great idea and I have voted for it.

**Comment by ToddLorey** [comment]
I just don't want it to get buried in the wishlist if it doesn't get enough attention.  There's already 7 votes so hopefully we get some traction!

**Comment by ResetXPDR** [comment]
I'll leave this issue up for a couple of days before closing it to give it a bit more visibility. I have also asked users over at Avsim to vote for this wishlist item.

**Comment by ToddLorey** [comment]
Maybe you could add something to the readme as well.  Right after your warning about not mentioning it in the forums.  Point people to the wishlist item to vote.  Just saying.  :)

**Comment by ResetXPDR** [comment]
Done.

**Comment by ToddLorey** [comment]
I think it's working.  :)

**Comment by ToddLorey** [comment]
Still waiting (>24hrs) for my post on Avsim to get moderator approval.  I thought I had an account and probably did a long time ago.  I posted a description of the symbol that was used for average in front of FPS.  The one that looks like null, that we're used to using it for.  Turns out, it actually is used for average in German speaking countries.  But I agree, it was confusing too many people.

**Comment by ResetXPDR** [comment]
Ah, that makes sense because I think the previous author, Fragtality, whom I inherited the code base from is German. In any case, the symbol is gone in the latest app version. Thanks for letting me know.

**Comment by ResetXPDR** [comment]
I'll close this out now since the readme provides the link to the wish list item near the top.
