### ISSUE TITLE
MSFS2020 AutoFPS 0.4.2  Error

### ISSUE THREAD

**Issue by mibo46** [ResetXPDR/MSFS2020_AutoFPS#35]
Hi,
Tried to download MSFS AutoFPS Installer (0.4.2) and  the Install button turns gray and an Error appears o my desktop:
Exception 'System.Net.WebException' during Download File. 
Have tried  several times and even with firewall turned off- it does not install!

**Comment by ResetXPDR** [comment]
Can you please post a screenshot of what you are seeing. Thanks.

**Comment by mibo46** [comment]
> Can you please post a screenshot of what you are seeing. Thanks.
Screenshot of what I see in downloading Auto FPS after clicking Instal Button:
![Screenshot 2024-03-19 181253](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/98842252/f6ed0916-c0ad-4e71-9fb5-f5f0ca826699)

and sometimes it says Error Excepton 'System.Net.WebException' during Donload File.
Have also downloaded windowsdesktop-runtime-7.0.17-win-x86

**Comment by mibo46** [comment]
This, as said comes on as error if I want to install MSFS-AutoFPS
![Screenshot 2024-03-19 182343](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/98842252/305b2941-730c-4f02-b043-bf8d39d9de71)

**Comment by ResetXPDR** [comment]
It seems to be getting stuck on installing .NET 7, which is a standard Windows component, not specific to the app. Try running the installer as admin, if you haven't already.

**Comment by ResetXPDR** [comment]
If that doesn't work, try manually installing .NET 7 which you can download from [here](https://dotnet.microsoft.com/en-us/download/dotnet/7.0).

**Comment by mibo46** [comment]
Thanks for your reply. 
I have Windows 11 and have downloaded the.Net Desktop Runtime 7.0.17 but it does not work..
Maybe it is not the right download because there are several different: SDK7, Core Runtime or .Net Runtime or as downloaded;  Net.Desktop Runtime






On Tuesday, March 19, 2024 at 08:00:06 PM AST, ResetXPDR ***@***.***> wrote: 







If that doesn't work, try manually installing .NET 7 which you can download from here.

**Comment by ResetXPDR** [comment]
[This ](https://download.visualstudio.microsoft.com/download/pr/8f5b0079-2bb4-49cd-874e-0f58703eff6e/7010b5f213a2c436a307eb385dbb16ff/windowsdesktop-runtime-7.0.14-win-x64.exe)is the file the installer is trying to download. Try installing it manually:

**Comment by mibo46** [comment]
Thank you very much, the download worked. 






On Wednesday, March 20, 2024 at 02:10:03 AM AST, ResetXPDR ***@***.***> wrote: 







This is the file the installer is trying to download. Try installing it manually:

**Comment by ResetXPDR** [comment]
Awesome. I will close this issue given you now are up and running.
