### ISSUE TITLE
Unable to Install Auto FPS

### ISSUE THREAD

**Issue by reazulalam** [ResetXPDR/MSFS2020_AutoFPS#38]
Hello, First of all I want to thank you for creating such an amazing project. I have recently heard of this project and found it very interesting and it can really help me getting a good FPS on my low specs computer. However, I was never able to install AUTO FPS. I have searched everything thats available in google and youtube even asked some folks on social media but nobody could give me a solution. Whenever I try to install Auto FPS, it says could not determine package path of mobiflight WASM/Event module. I have installed mobiflight, installed WASM (i am not sure if i did it correctly, i just installed it on my 'c' drive but i am not sure if its linked with MSFS) however, I am still getting the same error again and again. I have tried downloading all the version available but still nothing. Here is a screenshot of the issue I am facing.
![Screenshot 2024-03-24 222012](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/164774412/1b161e6c-7b0b-49e6-930e-78fab856f882)
I have also installed mobiflght connector, installed WASM module and updated the events. Also updated Hubhop presets.
![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/164774412/b8c0d070-f171-46c2-bcb9-a4d626b14112)

But even after every try I am still getting the same error. Is there any solution to this?

**Comment by Bavarello** [comment]
Cannot find the folder where MSFS 2020 is installed (such as apps).
You will have had some CTD with MSFS. Try Reset and Reset in Settings\Apps\Installed Apps

Then, try installing again

<img width="369" alt="image" src="https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/22433856/0379a473-4c05-4a88-bb01-cf2d31f9bc39">

**Comment by reazulalam** [comment]
OMG Thank you So much! I did it and it got installed finally! 
You are a life saver! 
![Screenshot 2024-03-25 002302](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/164774412/b7e4d502-183b-4a1f-bb02-7c05e51eddde)
![Screenshot 2024-03-25 002309](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/164774412/69227fac-7178-4631-be3a-3d188112181c)

**Comment by ResetXPDR** [comment]
@Bavarello Thank you for helping out with this. @reazulalam Given this appears to have resolved your issue, I will close this out.
