### ISSUE TITLE
.NET Desktop Runtime Issue

### ISSUE THREAD

**Issue by alanbeasy** [ResetXPDR/MSFS2020_AutoFPS#40]
I was having the following issue when opening MSFS2020_AutoFPS
![Screenshot 2024-03-26 124951](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/123238286/51137c3e-3e13-4a3e-ac54-c50d224fbf58)
But when I clicked "Yes" nothing happened.
Using Google I found the .NET Desktop Runtime Download page.
https://dotnet.microsoft.com/en-us/download/dotnet/7.0
![runtime](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/123238286/3b6531c1-96d9-4ab9-85bc-f4d0a17bcd8c)
I downloaded the installer and Installed.
![Screenshot 2024-03-26 132710](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/123238286/111bf256-79ae-4dac-8f96-f518519cc9b7)
After that MSFS2020_AutoFPS opened correctly

**Comment by ResetXPDR** [comment]
Some users are having to download and install .NET 7 manually like you have. I will add an entry to the readme to cover this possibility. Thanks for letting me know.
