### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by atsbob** [ResetXPDR/MSFS2020_AutoFPS#44]
Any chance we could go back to the old icon rather than the dog? Didn't realize at first that it was changed and I thought I had malware installed on my system.

**Comment by ResetXPDR** [comment]
Sorry, the current icon is IMO iconic and will not be changed back.

**Comment by itzblakebro** [comment]
> Sorry, the current icon is IMO iconic and will not be changed back.

"In your opinion" but screw the opinion of everyone else that uses your program? lol - all this is going to do is fire someone up to fork your little program and make a better version, without said doggo.

**Comment by rogerramjet54** [comment]
itzblakebro what an awful thing to say. If you don't know how to change an icon yourself on a program shortcut, Google how to do it. And while you are doing that, also Google "common decency."
