### ISSUE TITLE
I have a suggestion for an additional feature.

### ISSUE THREAD

**Issue by ddobagi810** [ResetXPDR/MSFS2020_AutoFPS#45]
First, thank you for creating Auto FPS.
I have a suggestion for an additional feature.
Minimize or turn off the program when the program presses X.
minimize or turn off the program when you press X.
Or you could make a minimize button and a turn off button.
I need to exit AutoFPS and go to the world map after finishing a flight due to CTD issues.
I know there are very few people like me, but if this is not too hard to do, I would appreciate it.

**Comment by ResetXPDR** [comment]
I did briefly look at this a while back and it was not as simple as it sounds to implement so I didn't go any further. In your case, all you need to do is to right click on the icon in the system tray and select exit and the app will close whenever you want it to.
