### ISSUE TITLE
Installer stops at "Extracting Application" with greyed out Install buttong

### ISSUE THREAD

**Issue by gliderpro3** [ResetXPDR/MSFS2020_AutoFPS#51]
![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/147260904/8d54e051-e48a-4952-af87-8d02cb5c5e09)

Installed Mobiflight and WASM module and it never created the desktop icon and just gets stuck on this screen.

**Comment by ResetXPDR** [comment]
The next step for the installer after the "Extracting Application ..." message is to extract the zip file, but if this fails you should get an error window pop up.

It is most likely a permissions issue, so perhaps try running the installer as admin and see if that gets it installed correctly.

**Comment by gliderpro3** [comment]
Thank you for your response.

Tried an admin install, same thing unfortunately.

**Comment by ResetXPDR** [comment]
You can manually install the app if you wish. 

If it is the 0.4.10 release version you are wanting to install:
- download the file zip package [here](https://github.com/ResetXPDR/MSFS2020_AutoFPS/blob/main/MSFS2020_AutoFPS.zip)
- create the following directory C:\Users\<username>\AppData\Roaming\MSFS2020_AutoFPS\bin and copy the contents of the downloaded zip file into it.
- right click on the exe file and select create shortcut.
- copy the newly created shortcut onto your desktop.
- run the app by using the new shortcut. The config file and log directory will be automatically created.

To uninstall from a manual install:
- Delete C:\Users\<username>\AppData\Roaming\MSFS2020_AutoFPS and all sub directories
- Delete the app shortcut from your desktop.

**Comment by gliderpro3** [comment]
That worked, thank you!
