### ISSUE TITLE
App sometimes stays running not connected to MSFS which is also running

### ISSUE THREAD

**Issue by spiroza** [ResetXPDR/MSFS2020_AutoFPS#52]
I think this could be due to my sim crashing.  AutoFPS stays running but can't connect to the sim.  I have to look up and notice it and shut it down and restart it.  Then all is well.  What would be nice is if my sim shuts down or dies it would shut down and restart with the sim but, that can't work because it has to be run as admin, right?

Spinora

**Comment by ResetXPDR** [comment]
The app should automatically shut down when MSFS closes normally, but doesn't always do so if MSFS crashes. You can also set the app to start when MSFS starts by choosing "Auto-start with MSFS" when you install it. All of this functionality should work without having to run as admin, but there are some users where admin mode is the only way the app will work.

**Comment by spiroza** [comment]
Thanks, maybe I'll try to reinstall it and try turning off "run as admin".
I don't run MSFS as admin so I can't think of a reason why this app would
need to be run that way.
