### ISSUE TITLE
Program crashes when checking any box in expert mode

### ISSUE THREAD

**Issue by Pandramodo** [ResetXPDR/MSFS2020_AutoFPS#53]
I have read the previous issues, but I'm not sure if the conditions are the same here. Whenever I click *any* box, say for example I didn't want to leave "Decrease Cloud Quality" on, the program crashes and won't open again.

I tried reinstalling and trying with other boxes to come to the same result

**Comment by ResetXPDR** [comment]
I haven't heard of this issue before. Which app version are you running? When you reinstalled, did you use the remove option first to completely remove it or did you just run the installer and update? If the latter, try a complete removal first using the installer.

Can you please post a copy of the contents of your log file. It is usually located in C:\Users\<username>\AppData\Roaming\MSFS2020_AutoFPS\bin\

**Comment by ResetXPDR** [comment]
Also, there should be an Event Viewer log for when the crash occurred. It should look something like this:

![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/156568588/f74f94cb-8bea-4c7d-beb1-377faea2cdb3)

If you do have one, please post a screenshot like above.

**Comment by Pandramodo** [comment]
Well, this is awkward. Now that I've installed it again, I can't seem to replicate the error, and it works just fine. There weren't any logs in the roaming folder or the event viewer either.

All I can say is that it was the latest version, I had the problem just a couple of days ago.

**Comment by ResetXPDR** [comment]
That's OK. Sometimes the config file gets corrupted and it crashes the app when it gets written to when changing a settings. Removing completely and reinstalling usually fixes it, as it sounds like you have experienced. I am glad you got it working and hope the app is useful for you.
