### ISSUE TITLE
AutoFPS does not launch anymore

### ISSUE THREAD

**Issue by MD-82** [ResetXPDR/MSFS2020_AutoFPS#56]
From one day to the next. It worked fine on May 29th, woke up on May 30th and nothing. 

If I open it, nothing shows up. No window, no process in task manager. I have tried;

- Running as administrator
- Running from the original .exe instead of the shortcut
- Reinstalling
- Making sure the exclusion was added.

If I double click it twice in a row, it opens just to tell me that AutoFPS is already running (critical error) because I tried opening it twice in a row. When I click OK on the error, AutoFPS disappears.

**Comment by ResetXPDR** [comment]
When reinstalling, make sure you use the remove option first to make sure
it is completely removed before running the installer again.

**Comment by MD-82** [comment]
Working again! Thanks a million ;-)
