### ISSUE TITLE
Stuck deleting old version

### ISSUE THREAD

**Issue by drewsaw** [ResetXPDR/MSFS2020_AutoFPS#58]
Application seems to be stuck at:
Checking Application State...
Deleting old Version...

**Comment by ResetXPDR** [comment]
I assume you are referring to running the installer. Try running the installer as admin. Failing that, in file explorer go to C:\Users\<username>\AppData\Roaming\ and delete the MSFS2020_AutoFPS directory then try again.

**Comment by drewsaw** [comment]
Running installer as Admin worked. Thanks!
