### ISSUE TITLE
User interface does not open - v0.4.2.16

### ISSUE THREAD

**Issue by dumpfbacke1411** [ResetXPDR/MSFS2020_AutoFPS#59]
Hello

As described above, the user interface does not open when the program is started. 

Setup is configured to start with the Sim.
Program is running in the background (I can see this in the task manager)
Setup was started as administrator.

See also screenshots.

![MSFS_AutoFPS - Setup_1](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/102235100/2bbff39c-3781-458d-9f7c-87379435e77a)
![MSFS_AutoFPS - Setup_2](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/102235100/aa882595-c8e5-42cc-9fce-13cf0d0d8824)

Thank you in advance for your feedback

**Comment by ResetXPDR** [comment]
Does the app icon appear in the system tray? If so, double click on it to open the window.
If not, try removing the app using the installer and reinstalling normally, ie. not as administrator.

**Comment by dumpfbacke1411** [comment]
Hello "ResetXPDR",

thank you for your feedback.

Yes, the app appears in the taskbar.

If you double-click on the app icon, it appears as shown in the screenshot. 

![MSFS_AutoFPS ](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/102235100/a862f436-10c6-483a-aef7-2d5bd48cb573)

However, the user interface (UI) does not appear after starting the MSFS2020, but the program runs in the background.

I have uninstalled and reinstalled the app several times, always with the same result.

I will try again without installing as admin. 

Thank you for your time

Klaus
--

**Comment by ResetXPDR** [comment]
When I said double click I meant on the icon in the system tray, not the app icon. In any case, I have had a similar issue myself on my dual screen system with the app window never showing when auto starting with MSFS. When I double click on the system tray icon, the window appears to start opening but with a destination somewhere off screen. The only way I can get it to work properly is remove the auto start with MSFS option and just manually start it myself, so I suggest you try that if all else fails.

**Comment by dumpfbacke1411** [comment]
toll, das Sie. Immer so prompt reagieren und Hilfestellung anbieten.
Ich hatte das schon verstanden mit dem Doppelklick des App-Symbols in der Taskleiste.
Aber auch der Tipp mit Dual-Monitor ist interessant,  denn ich habe auch so ein Setup (1x 3840x2160 4k primär und 1x 3440x1440 21:9, sekundär).
Werde weiter testen und berichten.

**Comment by dumpfbacke1411** [comment]
Sorry, here in Englisch.

It's great that you always respond so promptly and offer help.
I had already understood that with the double-click of the app icon in the taskbar.
But the tip about dual monitors is also interesting, because I also have such a setup (1x 3840x2160 4k primary and 1x 3440x1440 21:9, secondary).
I will continue testing and report back.

**Comment by dumpfbacke1411** [comment]
Hello again  "**_ResetXPDR_**" !

Just for your information !

Everything works now, thanks to your help.
The UI is now displayed again.

What have I done:

1. deleted the tool
2. restarted the system
3. reinstalled the tool **_without configured autostart_**
4. started the tool in the taskbar by double-clicking on

and, voila, everything is back as it should be. UI is displayed again.

Thanks again for your support and your time.
Great support here. Thanks for that.  

Many Greetings
Klaus
--
