### ISSUE TITLE
Steam takes control of the app

### ISSUE THREAD

**Issue by vulpesfeggari** [ResetXPDR/MSFS2020_AutoFPS#6]
Using auto-start with MSFS, Steam seems to adds its overlay on the app and freezes the app completely. 
![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/66118972/5a23ff79-bbfd-4583-abe6-e0e6d2fbbd85)

**Comment by ResetXPDR** [comment]
There's nothing I know of to do about that so I suggest you don't use auto
start. Re run the installer, select remove auto start, click update, close
the installer and you're done.

**Comment by alepouna** [comment]
Hi, just to follow up a bit, it seems that Windows and Steam (and other apps) treat this app as part of the MSFS Executable, which is why the steam overlay breaks so much. Other app overlays (like AMD performance, InteL one) also consider this the actual MSFS executable the MSFS it self.

**Comment by ResetXPDR** [comment]
That's interesting. Thanks for letting me know and I will keep it in mind for future testing.
