### ISSUE TITLE
Auto Clouds?

### ISSUE THREAD

**Issue by osilver98** [ResetXPDR/MSFS2020_AutoFPS#60]
Mod is a god send for many of us thankyou! Been wondering for a while if it'd be possible for you to implement a functionality which allows you to set a cloud quality setting depending on your altitude. Similar to TLOD and OLOD? I use Auto TLOD and would love to be able to set cloud as say medium or high when on the ground and have them at ultra during cruise or something. Just a thought,
> cheers!

**Comment by ResetXPDR** [comment]
As mentioned in the readme, I am no longer adding new functionality like this to the app for now. Nonetheless, I will add it to the wish list should I ever choose to restart development again.
