### ISSUE TITLE
Double click in a text field hides UI elements

### ISSUE THREAD

**Issue by thereprocase** [ResetXPDR/MSFS2020_AutoFPS#61]
The new double click UI functionality triggers whenever user clicks in a text field. Double-clicking text is common to 'select all.' A user who wants to adjust a numerical setting might double click to select the current text and begin overwriting new digits there. Instead, this hides the portion of the UI they're trying to interact with.

**Comment by ResetXPDR** [comment]
Your observation is correct. The simplest solution is to not double click on text fields and just mark the text with your mouse instead to achieve the same effect. If you do accidentally double click, just do it two more times to get the UI back to where it was.
