### ISSUE TITLE
Lost all settings?

### ISSUE THREAD

**Issue by jwvanderbeck** [ResetXPDR/MSFS2020_AutoFPS#63]
![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/161126/e52d0c91-5ea0-4b50-9bae-91fa45f3d81e)

I can't access ANY settings anymore.  They just vanished.  I've looked everywhere to see if there is something to press to expand them back up or something but nothing I can find :(

Is there a log file I can look at?

EDIT: Found the logs but didn't see anything that helped indicate my issue

**Comment by ResetXPDR** [comment]
You must have inadvertently activated the new double click to hide parts of the UI functionality, per the readme as follows:
- The user can progressively hide parts of the UI when the app window is double clicked anywhere that is not a control. The first double click will hide the expert settings section (if applicable), the second will hide the general settings section and a third double click will restore all hidden settings sections. The last state in use will be restored when next starting the app.

Just double click anywhere on the UI to change what is hidden or revealed. Avoid double clicking in future unless you actually want this to happen.

**Comment by jwvanderbeck** [comment]
Oh wow.  I don't recall double clicking anywhere but that certainly matches up with exactly what I saw.  The bottom settings just vanished then I moved the mouse up to the top and it vanished as well.

99% certain I Wasn't double clicking (I was in fact trying to mouse over things to see the tooltips) but doesn't really matter, now I know how to get them back :)

Thanks!
