### ISSUE TITLE
Window can't be restored

### ISSUE THREAD

**Issue by mikep987** [ResetXPDR/MSFS2020_AutoFPS#64]
When you close the window with the X button, the program continues to run but without a window.  If you then end the task from task Manager and try to start the application again, no window will be displayed but the program continues to run in the background and there is no way to restore the window.

**Comment by mikep987** [comment]
Saw a related post from another user.  I will look for the icon in the system tray from now on.  That should sovle it.  Thx

**Comment by ResetXPDR** [comment]
Yes, do not close the application using task manager as it doesn't shut down properly and can cause issues when restarting. If you ever get really stuck, just run the installer and remove it, then reinstall and it will be a fresh install.
