### ISSUE TITLE
SimConnect and Session stay red

### ISSUE THREAD

**Issue by farmaher** [ResetXPDR/MSFS2020_AutoFPS#66]
Hello, The current installed version is v4.2.16 with "Autostart with MSFS" activated. The official MS C++ packages for 2015-2022 has already been installed, but Simconnect and Sessions stay red after the game is fully loaded. The game is a Steam version. Please can you help. The log file is attached.

[MSFS2020_AutoFPS20240702.log](https://github.com/user-attachments/files/16068707/MSFS2020_AutoFPS20240702.log)

![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/35561612/8f065dd9-a688-4506-a1c4-83280a3330f4)

**Comment by ResetXPDR** [comment]
Someone else with a similar issue with MobiFlight WASM Module Exception 31 on the predecessor to this app [here](https://www.avsim.com/forums/topic/640425-msfs-adaptive-lod/?do=findComment&comment=5043431) fixed it by downloading and installing [this](https://github.com/MobiFlight/MobiFlight-WASM-Module/releases/tag/1.0.1), so I suggest you try that.

**Comment by farmaher** [comment]
Thanks for sharing. I have already tried this with no success, unfortunately. The mobiflight-event-module folder including contents (Hotfix 1.0.1)  extracted to the Community folder, PC restarted and I re-ran the MSFS2020 but SimConnect remained red.

**Comment by farmaher** [comment]
I have taken all these steps as per your GitHub instructions but couldn't make it work, unfortunately. Thanks for responding to me here.

**Comment by ResetXPDR** [comment]
No worries. This is the first time none of these suggestions have worked, so I'm a bit stumped on what else to suggest.

**Comment by twSimulations** [comment]
@farmaher You have to enable developer mode

**Comment by ResetXPDR** [comment]
The app should connect with SimConnect regardless of whether developer mode is enabled or not.

**Comment by oliveiralberto** [comment]
I am having the same issues. before was working fine for me.

**Comment by ResetXPDR** [comment]
> I am having the same issues. before was working fine for me.

What was different before when it was working?

**Comment by Diabeetus94** [comment]
i have also the same issue here dont know why this happened

**Comment by ResetXPDR** [comment]
> i have also the same issue here dont know why this happened the same is also for your other Programm DynamicLOD

Have you tried the suggestions in the [readme](https://github.com/ResetXPDR/MSFS2020_AutoFPS/blob/main/README.md#installation--update--uninstall) and the additional suggestions in this thread?

**Comment by ResetXPDR** [comment]
FYI, someone over at AVSIM was having this issue and it turned out to be a corrupt MSFS installation relating to Mobiflight, not AutoFPS specifically. The issue was resolved by reinstalling MSFS, so I am going to close this issue to that solution and will update the readme accordingly.
