### ISSUE TITLE
MSFS Auto already running

### ISSUE THREAD

**Issue by RGBrewer** [ResetXPDR/MSFS2020_AutoFPS#67]
After downloading latest update, app wont load. Only things i have open are chrome, task manager ... task manager shows autoFPS but it removes it immediately after clicking OK in the popup

![image](https://github.com/user-attachments/assets/ac3bd46d-9ce6-48ce-a954-91e182cf29a0)

**Comment by RGBrewer** [comment]
nm i found it in background processes -- failing to close cleanly maybe?

**Comment by RGBrewer** [comment]
Update: It is opening, but its just putting it in the system tray so you never know its opened. Would opening the main window on boot minimize confusion?

**Comment by ResetXPDR** [comment]
The app will remember the last state it was in when you close it and will open up that way, so if you had it minimised to the system tray on closure, that it how it will start next time.

If you want the app to start with the app window showing, make sure the window is showing when the app is closed. To exit the app with the window showing, either quit MSFS and it should auto close or right click on the system tray icon and left click on exit as shown.

![image](https://github.com/user-attachments/assets/06512ba7-8bf2-4db0-88d1-d1aa6e58ad45)

**Comment by ResetXPDR** [comment]
I am going to close this as the instructions given above should resolve the issue.
