### ISSUE TITLE
Alt OLOD Base cannot be set lower than 2000ft

### ISSUE THREAD

**Issue by D3V1L0M3N** [ResetXPDR/MSFS2020_AutoFPS#68]
It is impossible to set "Alt OLOD Base" to anything lower than 2000ft. Any input below 2000 reverts to 2000. Even editing the config file manually does not work. This is problematic for circuit flying where the traffic pattern is 1000ft AGL. In such cases we don't want OLOD @ Base active until on final, i.e. 600-800ft AGL.

**Comment by D3V1L0M3N** [comment]
Additionally, if one does attempt to manually edit the config file to set "AltOLODBase" to "800", when launching the program the AutoFPS window does not auto-display. (Though it will still be in taskbar and openable from there)

**Comment by ResetXPDR** [comment]
The minimum AltOLODBase is 1000. It was set to that a long time ago based on user feedback that setting it lower causes stutters on final.

**Comment by D3V1L0M3N** [comment]
Oh I see. Thanks! 🙂
