### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by eddiee2000** [ResetXPDR/MSFS2020_AutoFPS#7]
Hi I have left the download MSFS2020 AutoFPS as default but my flight sim keeps freezing I use VR a Pico 4 Headset and Virtual desktop app when I uninstall the MSFS 2020 AutoFPS the freezing stops. Any idea's????
Cheers Eddie

**Comment by ResetXPDR** [comment]
This is the first I have heard of an issue like this. Can you provide more details? Does it freeze when starting or running the app or just having it installed and not running? Are you using autorun? If so, have you tried not using autorun and just start the app manually?

**Comment by eddiee2000** [comment]
HiIt does use auto run so will try manual start. It happens normally after 5 to 10 mins in flight. I have not had this issue before. I only raise the issue to help as I know how much hard work you put in👍RegardsEddie EvesOn 28/02/2024 at 20:17, ResetXPDR wrote:
                
            
            
                
                    From: "ResetXPDR" ***@***.***>Date: 28 February 2024To: "ResetXPDR/MSFS2020_AutoFPS" ***@***.***>Cc: "Author" ***@***.***>,"eddiee2000" ***@***.***>Subject: Re: [ResetXPDR/MSFS2020_AutoFPS] Freezing (Issue #7)
                
                
This is the first I have heard of an issue like this. Can you provide more details? Does it freeze when starting or running the app or just having it installed and not running? Are you using autorun? If so, have you tried not using autorun and just start the app manually?

**Comment by ResetXPDR** [comment]
Thanks for letting me know. Keep me posted whether manually running the app instead of autostart resolves the issue. You can rerun the installer to remove autostart.

**Comment by eddiee2000** [comment]
Morning Thought issue might be little nav map so closed that, then noticed internet connection kept dropping out ( I have 1gb fibre to premises) but when I started MSFS2020 Auto FPS I got the followingRegardsEddie EvesOn 29/02/2024 at 05:44, ResetXPDR wrote:
                
            
            
                
                    From: "ResetXPDR" ***@***.***>Date: 29 February 2024To: "ResetXPDR/MSFS2020_AutoFPS" ***@***.***>Cc: "Author" ***@***.***>,"eddiee2000" ***@***.***>Subject: Re: [ResetXPDR/MSFS2020_AutoFPS] Freezing (Issue #7)
                
                
Thanks for letting me know. Keep me posted whether manually running the app instead of autostart resolves the issue. You can rerun the installer to remove autostart.

**Comment by ResetXPDR** [comment]
@eddiee2000 Your last message is garbled. Can you please re send the message directly on github here.

**Comment by ResetXPDR** [comment]
@eddiee2000 I am going to close this as you have raised another issue following on from this.
