### ISSUE TITLE
Losseless Scaling FPS "on top" in 4.3.1

### ISSUE THREAD

**Issue by Pinsho** [ResetXPDR/MSFS2020_AutoFPS#73]
Hello,
I updated the app to 4.3.1 and it seems is not detecting the Losseless Scaling FG ratio (always 1X in my case) using the "on top" feature, It always show the "real" FPS and not the LSFG FPS.
I downgraded the app to 4.3.0 and it worked properly, so I don't know if there is an issue whit the "on top" when using Losseless Scaling FG in 4.3.1.

NOTE for future improvements: When using different profiles in LS, AutoFPS only detects the LS Default profile settings. It would be great if Auto FPS would detect the configuration of the LS profile you are using in case you have different LS profiles.

**Comment by ResetXPDR** [comment]
I looked at the coded and the "on top" feature has nothing to do with LSFG detection and works completely independent of it. 0.4.3.0 and 0.4.3.1 should behave exactly the same in that regard. Also, per the readme, AutoFPS does detect a profile specifically named MSFS2020 in version 0.4.3.1:

- Lossless Scaling (LS) FG, including the scaling muliplier used, is also detected and the correct LSFG multiplied FPS is displayed. The app will first try to use an LS profile with the specific name MSFS2020 to obtain these settings. If an MSFS2020 profile does not exist then the settings in the Default profile will be used.

I just tested "on top" and LSFG detection worked fine either with the MSFS2020 or, if missing, the Default profile. Are you sure you have set up LS with a profile named "MSFS2020"? If you have and are still having this issue, please attach a copy of your LS config file called Settings.xml, which you can find in %localAppData%/Lossless Scaling.

**Comment by Pinsho** [comment]
Renaming the LS profile to MSFS2020 did the trick for me, but curiously AutoFPS detects the settings in the MSFS2020 profile (LSFG2.3 3x) but LS doesn't detect the MSFS2020 settings and apply the default settings (LSFG2.3 2x). I can't get the “Auto scale” option to work in LS, but that is not related to AutoFPS so I will investigate that.
Thanks!
[Settings.zip](https://github.com/user-attachments/files/17284238/Settings.zip)

**Comment by ResetXPDR** [comment]
> Renaming the LS profile to MSFS2020 did the trick for me, but curiously AutoFPS detects the settings in the MSFS2020 profile (LSFG2.3 3x) but LS doesn't detect the MSFS2020 settings and apply the default settings (LSFG2.3 2x). I can't get the “Auto scale” option to work in LS, but that is not related to AutoFPS so I will investigate that. Thanks! [Settings.zip](https://github.com/user-attachments/files/17284238/Settings.zip)

I see your default profile is named Por defecto (Spanish for Default according to Google translate), which may be why you are having an issue with the default profile as AutoFPS is looking for the specific name "Default" if "MSFS2020" isn't found.

I just tried using your Setting.xml (interestingly it renamed Por defecto to Default by itself automatically) and AutoFPS is detecting LSFG 3X from your MSFS2020 profile. Are you saying it is not showing 3X for you?

**Comment by Pinsho** [comment]
Yes, AutoFPS is now detecting LSFG 3X even in spanish :)
The problem now is LS is not detecting MSFS2020 profile and when scaling it applies the settings from the "Por defecto" profile, so there's nothing to do with AutoFPS. Auto scale feature in profiles seems very tricky to me...

**Comment by ResetXPDR** [comment]
It could be your MSFS path in your Settings.xml as it is showing the filter as:  <Path>*Flight*Simulator</Path>

On mine I don't specify a filter and it works fine. Maybe try that.

**Comment by ResetXPDR** [comment]
No worries. I'll leave you with it. As your AutoFPS-specific issue seems resolved. I will close this off now.

**Comment by ResetXPDR** [comment]
@Pinsho let me know if the LS issue does end up being something to do with having to name the profile MSFS2020 as I may need to change the profile name looks for to something else. Thanks.

**Comment by Pinsho** [comment]
> @Pinsho let me know if the LS issue does end up being something to do with having to name the profile MSFS2020 as I may need to change the profile name looks for to something else. Thanks.

sure!
