### ISSUE TITLE
AutoFPS deleting microsoft flight simulator

### ISSUE THREAD

**Issue by samstak07** [ResetXPDR/MSFS2020_AutoFPS#9]
Hello, I get this issue when it deletes the MSFS exe, basically the game itself. Also happens with DynamicLOD. Any help? Thanks.

**Comment by ResetXPDR** [comment]
The installer and app go nowhere near the actual MSFS executable or where it is located, so it must be something else sorry.

**Comment by ResetXPDR** [comment]
Thinking a bit more about this, it could possibly be your AV reacting to this app accessing MSFS memory while running, even though the app doesn't actually access the MSFS.exe file on your storage in any way, and quarantining your MSFS.exe file as a precaution. I suggest you check your AV program's quarantine list and see if that's where it has gone. If it is there, you could set an exclusion for MSFS and or this app in your AV program so this doesn't happen again. If you are not comfortable doing this, just uninstall both apps.
